### ISSUE TITLE
feature: Generic workflow call for automation

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/automation-seed#4]
We have different workflows that are doing exactly the same. That is why we need to create a separate action and call it on each existing workflow.

- [ ] Create a workflow at `.github/workflows/automation-call.yml` with the `workflow_call` trigger

The new workflow should have the following header:

```yml
permissions:
  contents: write

on:
  # This will allow us to reuse this workflow from other repos
  workflow_call:
    inputs:
      ref:
        description: Specifies from which ref to execute the automation.
        required: false
        type: string
        default: ""

      log_level:
        description: Specifies the log level
        required: true
        type: string
        default: 'info'

      suite:
        description: Suite to be executed
        default: ''
        type: string
        required: false

      spec:
        description: Spec to be executed. (Won't be used if suite is specified)
        default: ''
        type: string
        required: false

      spec_ci_index:
        description: Specifies the index of the spec in the CI environment
        default: 0
        type: number
        required: false

      spec_ci_total:
        description: Specifies the total number of specs in the CI environment
        default: 1
        type: number
        required: false

      max_instances:
        description: Maximum number of instances to be executed
        default: ''
        type: string
        required: false

      chrome_instances:
        description: Amount of Chrome Instances to be used. Won't use Chrome when its value is a blank string
        default: '1'
        type: string
        required: false

      firefox_instances:
        description: Amount of Firefox Instances to be used. Won't use Firefox when its value is a blank string
        default: ''
        type: string
        required: false

      browser_visible:
        description: Specifies whether the browser is visible on the Remote Dashboard. If false, the browsers will run in headless mode.
        type: string
        default: 'true'
        required: false

      enable_video:
        description: Specifies whether browser is recorded or not. Will be disabled if the browsers run in headless mode.
        type: string
        default: 'true'
        required: false

      update_report:
        description: Specifies whether the report is updated or not.
        type: string
        default: 'false'
        required: false
```
