### ISSUE TITLE
feature: Parallel Job execution using batches - Step 2

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/automation-seed#6]
Blocked by: #5 

Update the suite execution in the reusable workflow to support multiple splits using the following code as reference:

```yml
- name: Execute test Suite
  run: |
    SPEC_FILES=$(yarn --silent suite:files ${{ inputs.suite }} | sort | awk "NR % $CI_TOTAL_JOBS == $CI_JOB_INDEX")
    echo "Number of specs to be executed: $(echo $SPEC_FILES | wc -w)"
    [[ -z "$SPEC_FILES" ]] && exit 0
    echo "Running specs: $SPEC_FILES"
    echo $SPEC_FILES | xargs yarn test:remote --spec
  if: ${{ inputs.suite != '' }}
  env:
    OUTPUT_DIR: '../../logs'
    WEBDRIVER_LOGLEVEL: ${{ inputs.log_level }}
    BROWSER_VISIBLE: ${{ inputs.browser_visible }}
    ENABLE_VIDEO: ${{ inputs.enable_video }}
    MAX_INSTANCES: ${{ inputs.max_instances }}
    CHROME: ${{ inputs.chrome_instances }}
    FIREFOX: ${{ inputs.firefox_instances }}
    WEBDRIVER_SPEC_FILE_RETRIES: 1
    CI_JOB_INDEX: ${{ inputs.spec_ci_index }}
    CI_TOTAL_JOBS: ${{ inputs.spec_ci_total }}
```

**Comment by ulises-jeremias** [comment]
Expected usage example:

```yml
jobs:
  run-e2e-tests:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        jobs: [0, 1, 2, 3, 4]

    uses: ./.github/workflows/automation-exec.yml
    with:
      log_level: info
      suite: ci.pull_request
      spec_ci_index: ${{ matrix.jobs }}
      spec_ci_total: 5
      max_instances: 3
      chrome_instances: 2
      browser_visible: true
      enable_video: false
```
